INSERT INTO IIS.CATA_LIFER (
    PK_CL_PRISON_NUMBER,
    CL_INMATE_SURNAME,
    LIFER_STATUS,
    XIDBKEY,
    KSQ_CL_SURNAME_ID,
    KSQ_CATA_STATUS_ID
)

VALUES
    ('AB111111', '', 'LM', 12345, 12345, 12345);
