CREATE INDEX HPA_ADDRESSES
    ON HPA.ADDRESSES
    (
        PRISON_NUMBER
    ) INCLUDE (
    STREET, TOWN, COUNTY, TYPE, PERSON
)
    WITH (ONLINE = ON);
GO

CREATE INDEX HPA_COURT_HEARINGS
    ON HPA.COURT_HEARINGS
    (
        PRISON_NUMBER, DATE
    ) INCLUDE (
    COURT
)
    WITH (ONLINE = ON);
GO

CREATE INDEX HPA_HDC_INFO
    ON HPA.HDC_INFO
    (
        PRISON_NUMBER, DATE
    ) INCLUDE (
    STAGE, STATUS, REASONS
)
    WITH (ONLINE = ON);
GO

CREATE INDEX HPA_HDC_RECALL
    ON HPA.HDC_RECALL
    (
        PRISON_NUMBER, CREATED_DATE
    ) INCLUDE (
    CURFEW_END_DATE, OUTCOME_DATE, OUTCOME, REASON
)
    WITH (ONLINE = ON);
GO

CREATE INDEX HPA_MOVEMENTS
    ON HPA.MOVEMENTS
    (
        PRISON_NUMBER, DATE, TIME
    ) INCLUDE (
    TYPE, MOVEMENT, ESTABLISHMENT
)
    WITH (ONLINE = ON);
GO

CREATE INDEX HPA_OFFENCES
    ON HPA.OFFENCES
    (
        PRISON_NUMBER, DATE
    ) INCLUDE (
    CODE, ESTABLISHMENT
)
    WITH (ONLINE = ON);
GO

CREATE INDEX HPA_OFFENCES_IN_CUSTODY
    ON HPA.OFFENCES_IN_CUSTODY
    (
        PRISON_NUMBER, DATE
    ) INCLUDE (
    CHARGE, OUTCOME, ESTABLISHMENT
)
    WITH (ONLINE = ON);
GO

CREATE INDEX HPA_PERSONAL_DETAILS
    ON HPA.PERSONAL_DETAILS
    (
        PK_PRISON_NUMBER
    ) INCLUDE (
    PNC_NUMBER, CRO_NUMBER, PAROLE_NUMBERS, SURNAME, FORENAME_1, FORENAME_2, INITIAL,
    SEX, BIRTH_DATE, NATIONALITY, RELIGION, RECEPTION_DATE, MARITAL_STATUS
)
    WITH (ONLINE = ON);
GO

CREATE INDEX HPA_PRISONER_CATEGORY
    ON HPA.PRISONER_CATEGORY
    (
        PRISON_NUMBER
    ) INCLUDE (
    DATE, CATEGORY
)
    WITH (ONLINE = ON);
GO

CREATE INDEX HPA_SENTENCING
    ON HPA.SENTENCING
    (
        PRISON_NUMBER, CHANGE_DATE
    ) INCLUDE (
    LENGTH, SED, PED, NPD, LED, CRD, HDCAD, HDCED
)
    WITH (ONLINE = ON);
GO
