CREATE INDEX HPA_PRISONER_DETAILS
    ON HPA.PRISONER_DETAILS
    (
        PK_PRISON_NUMBER
    ) INCLUDE (
    PERSONAL_DETAILS,
    ADDRESSES,
    ALIASES,
    COURT_HEARINGS,
    HDC_INFO,
    HDC_RECALL,
    MOVEMENTS,
    OFFENCES,
    OFFENCES_IN_CUSTODY,
    SENTENCING
)
    WITH (ONLINE = ON);
GO
-- approx 2h
