CREATE INDEX HPA_KA_SEARCH ON IIS.KNOWN_AS
(
    PERSON_SURNAME,
    PERSON_FORENAME_1,
    PERSON_BIRTH_DATE,
    FK_PERSON_IDENTIFIER
)

CREATE INDEX HPA_LOL_SEARCH ON IIS.LOSS_OF_LIBERTY
(
    INMATE_SURNAME,
    INMATE_FORENAME_1,
    INMATE_BIRTH_DATE,
    FK_PERSON_IDENTIFIER
)

CREATE INDEX HPA_IDENT_SEARCH ON IIS.IIS_IDENTIFIER
(
    PERSON_IDENT_TYPE_CODE,
    PERSON_IDENTIFIER_VALUE,
    FK_PERSON_IDENTIFIER
)
