CREATE INDEX HPA_LOL_SEARCH_2 ON IIS.LOSS_OF_LIBERTY
(
    PK_PRISON_NUMBER,
    FK_PERSON_IDENTIFIER
)INCLUDE(
    DATE_1ST_RECEP,
    INMATE_SURNAME, INMATE_FORENAME_1, INMATE_FORENAME_2,
    INMATE_BIRTH_DATE
) WITH(ONLINE=ON);

CREATE INDEX HPA_KA_SEARCH_2 ON IIS.KNOWN_AS
(
    FK_PERSON_IDENTIFIER,
    PERSON_FORENAME_1,
    PERSON_FORENAME_2,
    PERSON_SURNAME,
    PERSON_BIRTH_DATE,
    PERSON_SEX
) WITH(ONLINE=ON);
