INSERT INTO IIS.LOSS_OF_LIBERTY (
    PK_PRISON_NUMBER,
    INMATE_SURNAME,
    INMATE_FORENAME_1,
    INMATE_FORENAME_2,
    INMATE_BIRTH_DATE,
    XIDBKEY
) VALUES
    ('12345678','Jameson','James','David','19801218',1.0);

INSERT INTO IIS.PERSON_REFERENCE (
    PK_PERSON_IDENTIFIER,
    XIDBKEY
) VALUES
    ('1234567891',1.0);

INSERT INTO IIS.LOSS_OF_LIBERTY (
    PK_PRISON_NUMBER,
    INMATE_SURNAME,
    INMATE_FORENAME_1,
    INMATE_FORENAME_2,
    INMATE_BIRTH_DATE,
    XIDBKEY,
    FK_PERSON_IDENTIFIER
) VALUES
    ('11111111', 'Alias', 'Have', 'I','19801230',1.0, '1234567891');

INSERT INTO IIS.KNOWN_AS (
    PKTS_KNOWN_AS,
    PERSON_FORENAME_1,
    PERSON_FORENAME_2,
    PERSON_SURNAME,
    PERSON_BIRTH_DATE,
    XIDBKEY,
    FK_PERSON_IDENTIFIER,
    SQ_REFERENCED_BY
) VALUES
    ('KNOWNAS', 'SURNAME','FORENAME1','FORENAME2','19801130',1.0,'1234567891','SQ_REFERENCED_BY');
